version: '3.8'
services:
  postgresql:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD='pwd123'
  go_check6:
      build: .
      environment:
        DB_ADDR: postgresql
      entrypoint: /main
      restart: always
      ports:
        - 50051:50051
