version: '3'
services:
  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    ports:
      - "54320:5432"
    networks:
      - "myNetwork"
  go_service:
    build: .
    depends_on:
      - pgdb
    entrypoint: /main
    restart: always
    ports:
      - 50051:50051
    networks:
      - "myNetwork"
networks:
  myNetwork:
